---
- name: Create Users & Groups
  hosts: test-server
  gather_facts: false
  become: true
  vars:
   - default_user_password: pass123

  tasks:
    - name: Create group
      group:
        name: admin_group
        state: present

    - name: Create Users Task
      user:
        name: "{{ item }}"
        state: present
        password: "{{ default_user_password | password_hash('sha512','A512') }}"
        shell: /bin/bash
        group: admin_group
      loop:
        - sam
        - jessica

---
 - name: Create users
   hosts: test-server
   remote_user: ansadmin

   tasks:
    - name: Add user
      user:
       name: joe
creates one user
---
- name: Create users
  hosts: test-server
  remote_user: ansadmin

  tasks:
  - var: item=joe
    user: name= "{{ item }}"  state= present

  - var: item=goerge
    user: name= "{{ item }}"  state= present

  - var: item=sam
    user: name= "{{ item }}"  state= present 

---
- name: Create users
  hosts: test-server
  remote_user: ansadmin

  tasks:
   - user: name= "{{ item }}"  state= present
     loop:
       - joe
       - gorge
       - ravi
       - mani
       - kiran
       - mike
       - rani
       
---
- name: Create users
  hosts: test-server
  remote_user: ansadmin

  tasks:
  - var: 
      item: joe
      uid: 1010
    user: name= '{{ item.name }}'  state= present uid='{{ item.uid}}'

  - var: 
      item: goerge
      uid: 1011
    user: name= '{{ item.name }}'  state= present uid='{{ item.uid}}'

  - var: 
      item: ravi
      uid: 1012
    user: name= '{{ item.name }}'  state= present uid='{{ item.uid}}'


---
- name: Create users
  hosts: test-server
  remote_user: ansadmin

  tasks:
   - user: name= "{{ item.name }}"  state= present  name= "{{ item.name }}"
     loop:
       - joe
       - gorge
       - ravi
       - mani
       - kiran
       - mike
       - rani
